import com.esotericsoftware.jsonbeans.Json;
import com.esotericsoftware.jsonbeans.OutputType;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	
	public static void main(String[] args) {
    
	System.out.println("FUNCIONA!!!!!");
	
//	// Serializador JSON
//    Json json = new Json(OutputType.json);
//
//    // Objeto para serializar inicializado
//    Object obj = new Object() {
//        int[] numeros;
//        String texto;
//
//        Object init() {
//            numeros = new int[] { 1, 2, 3 };
//            texto = "Mi texto";
//
//            return this;
//
//        }
//    }.init();

    // Salida por consola serializada en formato facil de leer
//    System.out.println(json.prettyPrint(obj));
	}

	public boolean someLibraryMethod() {
		// TODO Auto-generated method stub
		return false;
	}
}	